# jflat/cli_schema.py
"""
Command Line Interface (CLI) for flattening a *Pydantic JSON Schema*.

This file is meant to be beginner-friendly:
- It shows how to read a JSON file from disk
- It shows how to call our library code (the flattener)
- It prints the result, or optionally writes it to a file

How to run (from repo root):
    python -m jflat.cli_schema -h
    python -m jflat.cli_schema examples/schema.json
    python -m jflat.cli_schema examples/schema.json -o out.json
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from jflat.core.schema_flattener import PydanticSchemaFlattener


def main(argv: list[str] | None = None) -> int:
    """
    Entry point for the CLI.

    Why do we return an int?
    - In command-line programs, returning 0 means "success"
    - Non-zero means "something went wrong"
    This is standard for professional CLI tools and CI pipelines.
    """
    parser = argparse.ArgumentParser(
        prog="jflat.cli_schema",
        description="Flatten a Pydantic JSON Schema ($defs/$ref) into a teaching-friendly structure.",
    )

    # Positional argument: path to schema JSON
    parser.add_argument(
        "schema",
        type=Path,
        help="Path to a JSON Schema file generated by Pydantic (MyModel.model_json_schema()).",
    )

    # Optional argument: output file
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=None,
        help="If provided, write the flattened result to this JSON file instead of printing.",
    )

    args = parser.parse_args(argv)

    # --- 1) Read the input schema JSON file ---
    if not args.schema.exists():
        # Beginner-friendly error message
        print(f"ERROR: file not found: {args.schema}")
        return 2

    try:
        with args.schema.open("r", encoding="utf-8") as f:
            schema_dict = json.load(f)
    except json.JSONDecodeError as e:
        print(f"ERROR: input is not valid JSON: {args.schema}")
        print(f"Details: {e}")
        return 2

    # --- 2) Call our library code (flattener) ---
    try:
        flattener = PydanticSchemaFlattener(schema_dict)
        result_json = flattener.to_json(indent=2)  # JSON string for printing/writing
    except Exception as e:
        # In production you might use logging; for prototype we show clear errors
        print("ERROR: could not flatten schema.")
        print(f"Details: {e}")
        return 2

    # --- 3) Output ---
    if args.output:
        args.output.write_text(result_json, encoding="utf-8")
        print(f"✅ Wrote flattened schema to: {args.output}")
    else:
        print(result_json)

    return 0


# This block is the reason `python -m jflat.cli_schema ...` works:
# It runs only when executed as a script/module, not when imported in tests.
if __name__ == "__main__":
    raise SystemExit(main())
